"""added slug to forminfo

Revision ID: 0092b21e8bb4
Revises: 733f0d991082
Create Date: 2026-09-16 18:51:36.051167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0092b21e8bb4'
down_revision: Union[str, Sequence[str], None] = '733f0d991082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_info', sa.Column('slug', sa.String(), nullable=False))
    op.drop_index(op.f('ix_form_info_name'), table_name='form_info')
    op.create_index(op.f('ix_form_info_slug'), 'form_info', ['slug'], unique=True)
    op.create_unique_constraint(None, 'form_info', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'form_info', type_='unique')
    op.drop_index(op.f('ix_form_info_slug'), table_name='form_info')
    op.create_index(op.f('ix_form_info_name'), 'form_info', ['name'], unique=True)
    op.drop_column('form_info', 'slug')
    # ### end Alembic commands ###
