"""Added Favourite field to Contestants and Volunteers

Revision ID: 213cc3eda552
Revises: e897e297f868
Create Date: 2026-04-26 13:34:50.704552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213cc3eda552'
down_revision: Union[str, Sequence[str], None] = 'e897e297f868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contestants', sa.Column('favourite', sa.Boolean(), nullable=True))
    op.add_column('volunteers', sa.Column('favourite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteers', 'favourite')
    op.drop_column('contestants', 'favourite')
    # ### end Alembic commands ###
