"""fixed typo

Revision ID: 5f4a69ae45f6
Revises: 0092b21e8bb4
Create Date: 2026-09-16 19:07:47.166459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4a69ae45f6'
down_revision: Union[str, Sequence[str], None] = '0092b21e8bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_version', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('form_version', 'desription')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_version', sa.Column('desription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('form_version', 'description')
    # ### end Alembic commands ###
