"""Redid the form structure

Revision ID: 733f0d991082
Revises: 26536cff215c
Create Date: 2026-09-16 18:02:36.474023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '733f0d991082'
down_revision: Union[str, Sequence[str], None] = '26536cff215c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cur_version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_info_id'), 'form_info', ['id'], unique=False)
    op.create_index(op.f('ix_form_info_name'), 'form_info', ['name'], unique=True)
    op.create_table('form_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('version_num', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('desription', sa.String(), nullable=True),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['form_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_version_id'), 'form_version', ['id'], unique=False)
    op.create_table('form_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('form_version_id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['form_info.id'], ),
    sa.ForeignKeyConstraint(['form_version_id'], ['form_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_submission_id'), 'form_submission', ['id'], unique=False)
    op.drop_index(op.f('ix_viewers_id'), table_name='viewers')
    op.drop_table('viewers')
    op.drop_index(op.f('ix_contestants_id'), table_name='contestants')
    op.drop_table('contestants')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_volunteers_id'), table_name='volunteers')
    op.drop_table('volunteers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('school', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('class_and_profile', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rules_accepted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('privacy_policy_accepted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('facebook_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('favourite', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hidden', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('volunteers_pkey')),
    sa.UniqueConstraint('email', name=op.f('volunteers_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_volunteers_id'), 'volunteers', ['id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supervisor_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('supervisor_surname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('school', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('class_and_profile', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number_of_participants', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rules_accepted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('privacy_policy_accepted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('number_of_added_emails', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('favourite', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hidden', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('groups_pkey')),
    sa.UniqueConstraint('email', name=op.f('groups_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('contestants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('school', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('class_and_profile', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('supervisor_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('supervisor_surname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('supervisor_info', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('previous_accomplishments', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('about', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('interests', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contributions', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('inspiration', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('whytopic', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('whyinteresting', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('experience', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ways_of_grabing_interest', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('video_file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rules_accepted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('privacy_policy_accepted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('favourite', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hidden', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('contestants_pkey')),
    sa.UniqueConstraint('email', name=op.f('contestants_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_contestants_id'), 'contestants', ['id'], unique=False)
    op.create_table('viewers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('school', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('class_and_profile', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_contestant_close', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rules_accepted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('privacy_policy_accepted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('hidden', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('favourite', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('viewers_pkey')),
    sa.UniqueConstraint('email', name=op.f('viewers_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_viewers_id'), 'viewers', ['id'], unique=False)
    op.drop_index(op.f('ix_form_submission_id'), table_name='form_submission')
    op.drop_table('form_submission')
    op.drop_index(op.f('ix_form_version_id'), table_name='form_version')
    op.drop_table('form_version')
    op.drop_index(op.f('ix_form_info_name'), table_name='form_info')
    op.drop_index(op.f('ix_form_info_id'), table_name='form_info')
    op.drop_table('form_info')
    # ### end Alembic commands ###
