"""Standardized fav and hidden

Revision ID: 785dc8fd3d1f
Revises: c1664bc88339
Create Date: 2026-05-16 21:17:09.986554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785dc8fd3d1f'
down_revision: Union[str, Sequence[str], None] = 'c1664bc88339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('favourite', sa.Boolean(), nullable=True))
    op.add_column('groups', sa.Column('hidden', sa.Boolean(), nullable=True))
    op.add_column('viewers', sa.Column('favourite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viewers', 'favourite')
    op.drop_column('groups', 'hidden')
    op.drop_column('groups', 'favourite')
    # ### end Alembic commands ###
