"""initialPROD

Revision ID: 975b349ee6a3
Revises: 
Create Date: 2026-03-01 19:04:36.133683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '975b349ee6a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('contestants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('school', sa.String(), nullable=False),
    sa.Column('class_and_profile', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('supervisor_name', sa.String(), nullable=False),
    sa.Column('supervisor_surname', sa.String(), nullable=False),
    sa.Column('supervisor_info', sa.String(), nullable=False),
    sa.Column('previous_accomplishments', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=False),
    sa.Column('interests', sa.String(), nullable=False),
    sa.Column('contributions', sa.String(), nullable=False),
    sa.Column('inspiration', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('whytopic', sa.String(), nullable=False),
    sa.Column('whyinteresting', sa.String(), nullable=False),
    sa.Column('experience', sa.String(), nullable=False),
    sa.Column('ways_of_grabing_interest', sa.String(), nullable=False),
    sa.Column('video_file_path', sa.String(), nullable=True),
    sa.Column('rules_accepted', sa.Boolean(), nullable=False),
    sa.Column('privacy_policy_accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_contestants_id'), 'contestants', ['id'], unique=False)
    op.create_table('viewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('class_and_profile', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('is_contestant_close', sa.String(), nullable=False),
    sa.Column('rules_accepted', sa.Boolean(), nullable=False),
    sa.Column('privacy_policy_accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_viewers_id'), 'viewers', ['id'], unique=False)
    op.create_table('volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('school', sa.String(), nullable=False),
    sa.Column('class_and_profile', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('rules_accepted', sa.Boolean(), nullable=False),
    sa.Column('privacy_policy_accepted', sa.Boolean(), nullable=False),
    sa.Column('facebook_link', sa.String(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_volunteers_id'), 'volunteers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteers_id'), table_name='volunteers')
    op.drop_table('volunteers')
    op.drop_index(op.f('ix_viewers_id'), table_name='viewers')
    op.drop_table('viewers')
    op.drop_index(op.f('ix_contestants_id'), table_name='contestants')
    op.drop_table('contestants')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
