"""fill hidden with false

Revision ID: 9fdd71e98458
Revises: a5adfffb9473
Create Date: 2026-05-07 13:28:55.869501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fdd71e98458'
down_revision: Union[str, Sequence[str], None] = 'a5adfffb9473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE contestants SET hidden = FALSE WHERE hidden IS NULL"
    )
    op.execute(
        "UPDATE viewers SET hidden = FALSE WHERE hidden IS NULL"
    )
    op.execute(
        "UPDATE volunteers SET hidden = FALSE WHERE hidden IS NULL"
    )
    # ### end Alembic commands ###
    op.alter_column(
        'contestants', 'hidden', existing_type=sa.Boolean(), nullable=False, server_default=sa.false()
    )
    op.alter_column(
        'viewers', 'hidden', existing_type=sa.Boolean(), nullable=False, server_default=sa.false()
    )
    op.alter_column(
        'volunteers', 'hidden', existing_type=sa.Boolean(), nullable=False, server_default=sa.false()
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'contestants', 'hidden', existing_type=sa.Boolean(), nullable=True, server_default=None
    )
    op.alter_column(
        'viewers', 'hidden', existing_type=sa.Boolean(), nullable=True, server_default=None
    )
    op.alter_column(
        'volunteers', 'hidden', existing_type=sa.Boolean(), nullable=True, server_default=None
    )
    # ### end Alembic commands ###
