"""added hidden

Revision ID: a5adfffb9473
Revises: 213cc3eda552
Create Date: 2026-05-07 13:23:01.063899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5adfffb9473'
down_revision: Union[str, Sequence[str], None] = '213cc3eda552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contestants', sa.Column('hidden', sa.Boolean(), nullable=True))
    op.add_column('viewers', sa.Column('hidden', sa.Boolean(), nullable=True))
    op.add_column('volunteers', sa.Column('hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteers', 'hidden')
    op.drop_column('viewers', 'hidden')
    op.drop_column('contestants', 'hidden')
    # ### end Alembic commands ###
