"""Added number of added emails to groups

Revision ID: c1664bc88339
Revises: 63e6af3fbe5c
Create Date: 2026-05-11 17:38:43.788963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1664bc88339'
down_revision: Union[str, Sequence[str], None] = '63e6af3fbe5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('number_of_added_emails', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'number_of_added_emails')
    # ### end Alembic commands ###
