"""Added privacy policy accept

Revision ID: e897e297f868
Revises: fe55d7b91410
Create Date: 2026-03-01 15:48:47.519262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e897e297f868'
down_revision: Union[str, Sequence[str], None] = 'fe55d7b91410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contestants', sa.Column('privacy_policy_accepted', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.add_column('viewers', sa.Column('privacy_policy_accepted', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.add_column('volunteers', sa.Column('privacy_policy_accepted', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteers', 'privacy_policy_accepted')
    op.drop_column('viewers', 'privacy_policy_accepted')
    op.drop_column('contestants', 'privacy_policy_accepted')
    # ### end Alembic commands ###
