"""volunteers: +fb link, contestant story->inspiration sceptic->whyinteresting, viewer + is_contestant_close

Revision ID: fe55d7b91410
Revises: e1306c4be0dc
Create Date: 2026-02-28 20:11:28.216874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe55d7b91410'
down_revision: Union[str, Sequence[str], None] = 'e1306c4be0dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contestants', sa.Column('inspiration', sa.String(), nullable=False,server_default="brak"))
    op.add_column('contestants', sa.Column('whyinteresting', sa.String(), nullable=False,server_default="brak"))
    op.drop_column('contestants', 'persuation')
    op.drop_column('contestants', 'story')
    op.add_column('viewers', sa.Column('is_contestant_close', sa.String(), nullable=False,server_default="brak"))
    op.add_column('volunteers', sa.Column('facebook_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteers', 'facebook_link')
    op.drop_column('viewers', 'is_contestant_close')
    op.add_column('contestants', sa.Column('story', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('contestants', sa.Column('persuation', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('contestants', 'whyinteresting')
    op.drop_column('contestants', 'inspiration')
    # ### end Alembic commands ###
