"""added superadmin

Revision ID: ff57b7ba633b
Revises: 785dc8fd3d1f
Create Date: 2026-05-17 19:08:23.098336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff57b7ba633b'
down_revision: Union[str, Sequence[str], None] = '785dc8fd3d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('is_superadmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'is_superadmin')
    # ### end Alembic commands ###
